export const blockContainer: string;
export const goSettings: string;
export const blockTitle: string;
export const smallBlockTitle: string;
export const passwordChartsTypeRow: string;
export const passwordChartsTypeBlock: string;
export const notificationContainer: string;
export const notificationBlock: string;
export const largeMarginTop: string;
