export const background: string;
export const card: string;
export const cardActive: string;
export const cardNumber: string;
export const cardHolder: string;
export const cardHolderName: string;
export const expires: string;
export const expiredDate: string;
export const cardSecond: string;
